### ISSUE TITLE
Roadmap is 404

### ISSUE THREAD

**Issue by Phil9l** [homanp/superagent#108]
### What piece of documentation is affected?

Roadmap points to https://github.com/users/homanp/projects/4 which is 404.

### What part(s) of the article would you like to see updated?

Roadmap

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@Phil9l hmm I don't get a 404 when pressing on the link: https://github.com/users/homanp/projects/4

**Comment by homanp** [comment]
@Phil9l it was private 😄 Fixed now.
