### ISSUE TITLE
Add support for batch uploading datasources

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#415]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A user should be able to batch upload datasource via the API and SDK.

**TODO**
Create a new endpoint in `/lib/superagent/api/datasources.py` that batch creates datasources

```bash
await prisma.datasource.create_many(data=[...])
```
Reference: https://github.com/homanp/superagent/blob/v0.1.4/libs/superagent/app/api/datasources.py#L21

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
This is currently not possible due the limitations of OpenAI text embedding model rate limit.

**Comment by homanp** [comment]
This is fixed in #649
